version: '3'

services:

  mysql:
    # platform: linux/x86_64
    image: mysql:8.0
    restart: always
    container_name: go-template
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci --sql-mode=""
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: go-template
      MYSQL_ROOT_PASSWORD: root